# Generated by Django 3.2.13 on 2023-07-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='categoria',
            field=models.CharField(help_text='Categoria vehiculo ', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='last_edit',
            field=models.DateTimeField(auto_now=True, help_text='Fecha ultima modificación'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(help_text='Seleccione Marca: ', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(help_text='Seleccione Modelo ', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='precio',
            field=models.PositiveIntegerField(default=0, help_text='precio vehiculo: '),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha Creacion'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='serial_carroceria',
            field=models.CharField(help_text='Serial serial_carroceria: ', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='serial_motor',
            field=models.CharField(help_text=' serial motor: ', max_length=50),
        ),
    ]
