# Generated by Django 3.2.13 on 2023-07-06 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_auto_20230705_2358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': [('visualizar_catalogo', 'Visualizar Catalogos')]},
        ),
    ]
