# Generated by Django 3.2.13 on 2023-07-07 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_alter_vehiculo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='condición_precio',
            field=models.CharField(default='', max_length=20),
        ),
    ]
